# Generated by Django 3.2 on 2021-05-18 12:58

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('postdate', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('business', 'ビジネス'), ('Life', '生活'), ('other', 'その他')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SRMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRM_date', models.DateField(default=datetime.datetime(2021, 5, 18, 21, 58, 31, 874995), help_text='昨就寝の時間', serialize=False)),
                ('action_time1', models.TimeField(default='21:00:00', help_text='昨就寝の時間')),
                ('action_value1', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='昨就寝の活動量 0～3', null=True)),
                ('action_time2', models.TimeField(default='04:30:00', help_text='起床の時間')),
                ('action_value2', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='起床の活動量 0～3', null=True)),
                ('action_time3', models.TimeField(default='06:30:00', help_text='接触の時間')),
                ('action_value3', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='接触の活動量 0～3', null=True)),
                ('action_time4', models.TimeField(default='09:00:00', help_text='集団の時間')),
                ('action_value4', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='集団の活動量 0～3', null=True)),
                ('action_time5', models.TimeField(default='18:30:00', help_text='夕食の時間')),
                ('action_value5', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='夕食の活動量 0～3', null=True)),
                ('action_time6', models.TimeField(default='12:00:00', help_text='#6の時間')),
                ('action_value6', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='#6の活動量 0～3', null=True)),
                ('action_time7', models.TimeField(default='12:00:00', help_text='#7の時間')),
                ('action_value7', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='#7の活動量 0～3', null=True)),
                ('action_time8', models.TimeField(default='12:00:00', help_text='#8の時間')),
                ('action_value8', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='#8の活動量 0～3', null=True)),
                ('action_time9', models.TimeField(default='12:00:00', help_text='#9の時間')),
                ('action_value9', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='#9の活動量 0～3', null=True)),
                ('action_time10', models.TimeField(default='12:00:00', help_text='#10の時間')),
                ('action_value10', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=None, help_text='#10の活動量 0～3', null=True)),
                ('mood_value', models.IntegerField(blank=True, choices=[(-5, -5), (-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None, help_text='気分の値 -5～5', null=True)),
                ('ivent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SRMOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRM_name3', models.CharField(blank=True, default='接触', max_length=20)),
                ('SRM_name4', models.CharField(blank=True, default='集団', max_length=20)),
                ('SRM_name5', models.CharField(blank=True, default='夕食', max_length=20)),
                ('SRM_name6', models.CharField(blank=True, max_length=20)),
                ('SRM_name7', models.CharField(blank=True, max_length=20)),
                ('SRM_name8', models.CharField(blank=True, max_length=20)),
                ('SRM_name9', models.CharField(blank=True, max_length=20)),
                ('SRM_name10', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StPointModel',
            fields=[
                ('point_date', models.DateField(default=django.utils.timezone.now, help_text='日付', primary_key=True, serialize=False)),
                ('point1', models.BooleanField(default='Flase')),
                ('point2', models.BooleanField(default='Flase')),
                ('point3', models.BooleanField(default='Flase')),
                ('point4', models.BooleanField(default='Flase')),
                ('point5', models.BooleanField(default='Flase')),
                ('point6', models.BooleanField(default='Flase')),
                ('point7', models.BooleanField(default='Flase')),
                ('point8', models.BooleanField(default='Flase')),
                ('point9', models.BooleanField(default='Flase')),
                ('point10', models.BooleanField(default='Flase')),
                ('point11', models.BooleanField(default='Flase')),
                ('point12', models.BooleanField(default='Flase')),
                ('point13', models.BooleanField(default='Flase')),
                ('point14', models.BooleanField(default='Flase')),
                ('point15', models.BooleanField(default='Flase')),
                ('point16', models.BooleanField(default='Flase')),
                ('point17', models.BooleanField(default='Flase')),
                ('point18', models.BooleanField(default='Flase')),
                ('point19', models.BooleanField(default='Flase')),
                ('point20', models.BooleanField(default='Flase')),
                ('point21', models.BooleanField(default='Flase')),
                ('point22', models.BooleanField(default='Flase')),
                ('point23', models.BooleanField(default='Flase')),
                ('point24', models.BooleanField(default='Flase')),
                ('point25', models.BooleanField(default='Flase')),
                ('point26', models.BooleanField(default='Flase')),
                ('point27', models.BooleanField(default='Flase')),
                ('point28', models.BooleanField(default='Flase')),
                ('point29', models.BooleanField(default='Flase')),
                ('point30', models.BooleanField(default='Flase')),
            ],
        ),
        migrations.CreateModel(
            name='StPointNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.TextField()),
                ('category', models.TextField(blank=True, choices=[('1', '焦り'), ('2', '睡眠不足'), ('3', '生活リズム'), ('4', 'イライラ'), ('5', '他人の仕事'), ('6', '不要な共感'), ('7', '過食'), ('8', '疲れ'), ('9', '怒り'), ('10', '我慢')], verbose_name='分類')),
                ('point', models.IntegerField(default=30, help_text='1～100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('category', models.TextField(blank=True, choices=[('always', 'いつでも'), ('Sad', '悲しい時に送る言葉'), ('Sleepless', '眠っていない'), ('high', '躁度が高い'), ('low', '躁度が低い'), ('angry', 'イライラしている'), ('hurry', '焦っている')], verbose_name='どんな時にかけたい言葉ですか？')),
            ],
        ),
    ]
